apiVersion: skaffold/v2beta1
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "v0.1.0"
  artifacts:
  - image: unicell/ebpf_exporter
    context: ./
    docker:
      dockerfile: Dockerfile
  local:
    push: false
profiles:
  - name: release
    build:
      local:
        push: true
